/* DROP ���̺� */
DROP TABLE B_CAL CASCADE CONSTRAINTS;
DROP TABLE M_CAL CASCADE CONSTRAINTS;
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE CTA_CHARGE CASCADE CONSTRAINTS;
DROP TABLE CTA CASCADE CONSTRAINTS;
DROP TABLE MYPOINT CASCADE CONSTRAINTS;
DROP TABLE POINT CASCADE CONSTRAINTS;
DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS;
DROP TABLE REVIEW_COMMENT CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE QNA_COMMENT CASCADE CONSTRAINTS;
DROP TABLE QNA_BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL_IMAGE CASCADE CONSTRAINTS;
DROP TABLE HOS_PAY CASCADE CONSTRAINTS;
DROP TABLE HOS_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE MEDICAL_TYPE CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL CASCADE CONSTRAINTS;
DROP TABLE HAIR_SALON_IMG CASCADE CONSTRAINTS;
DROP TABLE HAR_PAY CASCADE CONSTRAINTS;
DROP TABLE HAR_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE STYLE CASCADE CONSTRAINTS;
DROP TABLE HAIR_SALON CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE PET_INFO CASCADE CONSTRAINTS;
DROP TABLE CHATROOM CASCADE CONSTRAINTS;
DROP TABLE CHATMESSAGE CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_PARTNER CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BUSINESS_PARTNER;
DROP SEQUENCE SEQ_CLIENT;
DROP SEQUENCE SEQ_ANNOUNCEMENT;
DROP SEQUENCE SEQ_QNA_BOARD;
DROP SEQUENCE SEQ_QNA_COMMENT;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_REVIEW_COMMENT;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_COMMENT;
DROP SEQUENCE SEQ_CHAT_ROOMID;
DROP SEQUENCE SEQ_CHAT_MESSAGE;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_CTA;
DROP SEQUENCE SEQ_CTA_CHARGE;
DROP SEQUENCE SEQ_LIKES;
DROP SEQUENCE SEQ_PET_INFO;
DROP SEQUENCE SEQ_HAIR_SALON;
DROP SEQUENCE SEQ_HAIR_SALON_IMG;
DROP SEQUENCE SEQ_HAIR_SALON_DAYOFF;
DROP SEQUENCE SEQ_HAR_RESERVATION;
DROP SEQUENCE SEQ_HAR_PAY;
DROP SEQUENCE SEQ_LIKES;
DROP SEQUENCE SEQ_STYLE;
DROP SEQUENCE SEQ_HOSPITAL;
DROP SEQUENCE SEQ_HOS_RESERVATION;
DROP SEQUENCE SEQ_HOS_PAY;
DROP SEQUENCE SEQ_MEDICAL_TYPE;

--------------------------------------------------------------------------------------------------

/* SEQUENCE */
CREATE SEQUENCE SEQ_BUSINESS_PARTNER
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CLIENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_ANNOUNCEMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_QNA_BOARD
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_QNA_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_REVIEW
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_BOARD
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_BOARD_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CHAT_ROOMID
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE SEQ_CHAT_MESSAGE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_NOTICE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_POINT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_MYPOINT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CTA
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CTA_CHARGE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_LIKES
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_PET_INFO
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAIR_SALON
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAIR_SALON_DAYOFF
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAIR_SALON_IMG
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;
CREATE SEQUENCE SEQ_HAR_RESERVATION
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAR_PAY
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_LIKES
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_STYLE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOSPITAL
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOSPITAL_IMG
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOSPITAL_DAYOFF
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOS_RESERVATION
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOS_PAY
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_MEDICAL_TYPE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;


-----------------------------------------------------------------------------------------------

/* ADMIN ���̺�  */
CREATE TABLE ADMIN( 
    ADMIN_ID VARCHAR2(50) CONSTRAINT MANAGER_MEG_EMAIL_PK PRIMARY KEY,
    ADMIN_PWD VARCHAR2(30) NOT NULL 
);


/* BUSINESS_PARTNER ���̺� */
CREATE TABLE BUSINESS_PARTNER ( 
    BP_ID VARCHAR2(20) CONSTRAINT BUSINESS_PARTNER_BP_ID_PK PRIMARY KEY, 
    BP_PWD VARCHAR2(30) NOT NULL, 
    BP_NAME VARCHAR2(20) NOT NULL, 
    BP_TEL VARCHAR2(20) NOT NULL UNIQUE, 
    BP_BANK VARCHAR2(20) NOT NULL, 
    BP_ACNT VARCHAR2(20) NOT NULL , 
    BP_EMAIL VARCHAR2(20) NOT NULL UNIQUE,
    BP_NUM VARCHAR2(20) NOT NULL,
    BP_TYPE NUMBER(1) NOT NULL,
    BP_APRVE NUMBER(1) DEFAULT 0 NOT NULL,
    BP_DELETE NUMBER(1) DEFAULT 0 NOT NULL
);



/* CLIENT ���̺�  */
CREATE TABLE CLIENT (
    CL_NUM VARCHAR2(20) CONSTRAINT CLIENT_CL_NUM_PK PRIMARY KEY,
    CL_EMAIL VARCHAR2(20) NOT NULL UNIQUE,
    CL_PWD VARCHAR2(30) NOT NULL,
    CL_NICKNAME VARCHAR2(20) NOT NULL,
    CL_NAME VARCHAR2(20) NOT NULL,
    CL_TEL VARCHAR2(20) NOT NULL UNIQUE
);



/* PET_INFO ���̺�  */
CREATE TABLE PET_INFO (
    PET_NUM VARCHAR2(20) CONSTRAINT PET_INFO_PET_NUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT PET_INFO_CL_NUM_FK REFERENCES CLIENT,
    PET_NAME VARCHAR2(20) NOT NULL,
    PET_KIND VARCHAR2(20) NOT NULL,
    PET_BIRTH VARCHAR2(20) NOT NULL,
    PET_GEN VARCHAR2(20) NOT NULL,
    PET_NEUT NUMBER(1),
    PET_EXPER VARCHAR2(20),
    PET_VACCIN VARCHAR2(20),
    PET_BITE VARCHAR2(20),
    PET_OTHERS VARCHAR2(20),
    PET_IMG VARCHAR2(20),
    MBTI VARCHAR2(20)
);

/* MESSAGE ���̺�  */
CREATE TABLE MESSAGE (
    MSG_NUM VARCHAR2(20) CONSTRAINT MESSAGE_MSG_NUM_PK PRIMARY KEY,
    MSG_CONT VARCHAR2(200) NOT NULL
);


/* MY_MESSAGE ���̺�  */
CREATE TABLE MY_MESSAGE (
    MSG_NUM VARCHAR2(20) CONSTRAINT MY_MESSAGE_MSG_NUM_FK REFERENCES MESSAGE,
    CL_NUM VARCHAR2(20) CONSTRAINT MY_MESSAGE_CL_NUM_FK REFERENCES CLIENT
    NOT NULL,
    MSG_DATE VARCHAR2(200) NOT NULL
);


/* NOTICE ���̺�  */
CREATE TABLE NOTICE (
    NOTICE_NUM VARCHAR2(20) PRIMARY KEY,
    NOTICE_CONTENT VARCHAR(20),
    NOTICE_RECEIVER VARCHAR2(20),
    NOTICE_PUBLISHER VARCHAR2(20),
    REFERENCE_NUM VARCHAR2(20),
    REFERENCE_CLASS VARCHAR2(20),
    READ_STATE NUMBER(1)
);


/* HAIR_SALON ���̺� */
CREATE TABLE HAIR_SALON (
    HAR_NUM VARCHAR2(40) CONSTRAINT HAIR_SALON_HAR_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT HAIR_SALON_BP_ID_FK REFERENCES BUSINESS_PARTNER NOT NULL,
    HAR_NAME VARCHAR2(20) NOT NULL,
    HAR_ADDR VARCHAR2(300) NOT NULL,
    HAR_TEL VARCHAR2(20) NOT NULL,
    HOPEN_TIME VARCHAR2(100) NOT NULL,
    HAR_MINFO VARCHAR2(500) NOT NULL,
    HAR_MIMG VARCHAR2(500) NOT NULL
);



/* STYLE ���̺�  */
CREATE TABLE STYLE (
    STYLE_NUM VARCHAR2(20) CONSTRAINT STYLE_STYLE_NUM_PK PRIMARY KEY,
    HAR_NUM VARCHAR2(20) CONSTRAINT STYLE_HAR_NUM_FK REFERENCES HAIR_SALON
    NOT NULL,
    STYLE_NAME VARCHAR2(200) NOT NULL,
    PRICE NUMBER(7) NOT NULL,
    STYLE_TIME NUMBER(3),
    STYLE_DEEP NUMBER(1) DEFAULT 0 NOT NULL
);



/* HAR_RESERVATION ���̺�  */
CREATE TABLE HAR_RESERVATION (
    HAR_RNUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_HAR_RNUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_CL_NUM_FK REFERENCES CLIENT
    NOT NULL,
    PET_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_PET_NUM_FK REFERENCES     
    PET_INFO NOT NULL,
    STYLE_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_STYLE_NUM_FK REFERENCES 
    STYLE NOT NULL,
    HAR_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_HAR_NUM_FK REFERENCES 
    HAIR_SALON NOT NULL,
    RES_DATE VARCHAR2(50) NOT NULL
);


/* HAR_PAY ���̺�  */
CREATE TABLE HAR_PAY (
    PAY_NUM VARCHAR2(20) CONSTRAINT HAR_PAY_PAY_NUM_PK PRIMARY KEY,
    HAR_RNUM VARCHAR2(20) CONSTRAINT HAR_PAY_HAR_RNUM_FK REFERENCES HAR_RESERVATION
    NOT NULL,
    CARD_NUM VARCHAR2(20) NOT NULL,
    BANK_NUM VARCHAR2(20) NOT NULL,
    CARD_NAME VARCHAR2(20) NOT NULL,
    BANK_NAME VARCHAR2(20) NOT NULL,
    PAY_DATE VARCHAR2(20) NOT NULL,
    PAY_PRICE NUMBER(7) NOT NULL,
    TOTAL_PRICE NUMBER(7) NOT NULL
);

/* HAIR_SALON_IMG ���̺�  */
CREATE TABLE HAIR_SALON_IMG (
    IMG_NUM VARCHAR2(20) PRIMARY KEY,
    HAR_NUM VARCHAR2(20) CONSTRAINT HAIR_SALON_IMG_HAR_NUM_FK REFERENCES HAIR_SALON,
    HAR_IMG VARCHAR2(500)
);


/* HOSPITAL ���̺�  */
CREATE TABLE HOSPITAL (
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_HOS_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT HOSPITAL_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    HOS_NAME VARCHAR2(40) NOT NULL,
    HOS_ADDR VARCHAR2(300) NOT NULL,
    HOS_TEL VARCHAR2(20) NOT NULL,
    OPEN_TIME VARCHAR2(20) NOT NULL,
    HOS_MINFO VARCHAR2(20) NOT NULL,
    HOS_MIMG VARCHAR2(500) NOT NULL
);


/* MEDICAL_TYPE ���̺�  */
CREATE TABLE MEDICAL_TYPE (
    MED_NUM VARCHAR2(20) CONSTRAINT MEDICAL_TYPE_MED_NUM_PK PRIMARY KEY,
    MED_NAME VARCHAR2(500) NOT NULL,
    MED_PRICE NUMBER(7) NOT NULL,
    HOS_NUM VARCHAR2(20) CONSTRAINT MEDICAL_TYPE_HOS_NUM_FK REFERENCES HOSPITAL
);


/* HOS_RESERVATION ���̺�  */
CREATE TABLE HOS_RESERVATION (
    HOS_RNUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_HOS_RNUM_PK PRIMARY KEY,
    PET_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_PET_NUM_FK REFERENCES PET_INFO,
    CL_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_CL_NUM_FK REFERENCES CLIENT,
    MED_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_MED_NUM_FK REFERENCES MEDICAL_TYPE,
    HOS_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_HOS_NUM_FK REFERENCES HOSPITAL,
    HOS_DATE VARCHAR2(50) NOT NULL
);

/* HOS_PAY ���̺�  */
CREATE TABLE HOS_PAY (
    PAY_NUM VARCHAR2(20) CONSTRAINT HOS_PAY_PAY_NUM_PK PRIMARY KEY,
    HOS_RNUM VARCHAR2(20) CONSTRAINT HOS_PAY_HOS_RNUM_FK REFERENCES HOS_RESERVATION NOT NULL,
    CARD_NUM VARCHAR2(20),
    BANK_NUM VARCHAR2(20),
    CARD_NAME VARCHAR2(20),
    BANK_NAME VARCHAR2(20),
    PAY_DATE VARCHAR2(20) NOT NULL,
    PAY_PRICE NUMBER(7) NOT NULL,
    TOTAL_PRICE NUMBER(7)
);


/* HOSPITAL_IMAGE ���̺�  */
CREATE TABLE HOSPITAL_IMAGE (
    IMG_NUM VARCHAR2(20) PRIMARY KEY,
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_IMAGE_HOS_NUM_FK REFERENCES HOSPITAL,
    HOS_IMG VARCHAR2(500)
);


/* BOARD ���̺�  */
CREATE TABLE BOARD ( 
    BO_NUM VARCHAR2(20) CONSTRAINT BOARD_BO_NUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) NOT NULL CONSTRAINT BOARD_CL_NUM_FK REFERENCES CLIENT,
    CL_NICKNAME VARCHAR2(20) NOT NULL,
    BO_TITLE VARCHAR2(100) NOT NULL,
    BO_CONT VARCHAR2(3000) NOT NULL,
    BO_IMG VARCHAR2(200),
    BO_DATE VARCHAR2(20) DEFAULT SYSDATE NOT NULL,
    BO_VIEW NUMBER(10) DEFAULT 0 NOT NULL,
    BOC_CHK NUMBER(5) DEFAULT 0 NOT NULL
);


/* B_COMMENT ���̺�  */
CREATE TABLE BOARD_COMMENT ( 
    CO_NUM VARCHAR2(20) CONSTRAINT BOARD_COMMENT_CO_NUM_PK PRIMARY KEY,
    BO_NUM VARCHAR2(20) NOT NULL CONSTRAINT BOARD_COMMENT_CO_NUM_BO_NUM_FK REFERENCES BOARD ON DELETE CASCADE,
    CL_NUM VARCHAR2(20) NOT NULL CONSTRAINT BOARD_COMMENT_CL_NUM_FK REFERENCES CLIENT,
    CL_NICKNAME VARCHAR2(20) NOT NULL,
    CO_CONT VARCHAR2(1000) NOT NULL,
    CO_DATE VARCHAR2(20) NOT NULL
);


/* QNA_BOARD ���̺�  */
CREATE TABLE QNA_BOARD ( 
    QNA_NUM VARCHAR2(10) CONSTRAINT QNA_BOARD_QNA_NUM_PK PRIMARY KEY,
    USER_NUM VARCHAR2(20) NOT NULL,
    QNA_TITLE VARCHAR2(100) NOT NULL,
    QNA_CONT VARCHAR2(3000) NOT NULL,
    QNA_IMG VARCHAR2(200),
    QNA_DATE VARCHAR2(20) NOT NULL,
    QNA_WR VARCHAR2(50) NOT NULL,
    QNA_TYPE NUMBER(1) NOT NULL,
    QNAR_CHK NUMBER(1) DEFAULT 0 NOT NULL
);


/* QNA_COMMENT ���̺�  */
CREATE TABLE QNA_COMMENT ( 
    QNAC_NUM VARCHAR2(10) CONSTRAINT QNAC_COMMENT_QNAR_NUM_PK PRIMARY KEY, 
    ADMIN_ID VARCHAR2(50) CONSTRAINT QNA_COMMENT_ADMIN_ID_FK REFERENCES ADMIN, 
    QNA_NUM VARCHAR2(50) CONSTRAINT QNA_COMMENT_QNA_NUM_FK REFERENCES QNA_BOARD ON DELETE CASCADE, 
    QNAC_CONT VARCHAR2(1000), 
    QNAC_DATE VARCHAR2(20) 
);


/* REVIEW ���̺� */
CREATE TABLE REVIEW (
    REV_NUM VARCHAR2(20) CONSTRAINT REVIEW_REV_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT REVIEW_BP_ID_FK REFERENCES BUSINESS_PARTNER
    ON DELETE CASCADE NOT NULL,
    CL_NUM VARCHAR2(20),
    CL_NICKNAME VARCHAR(20),
    REV_CONT VARCHAR2(3000),
    REV_IMG VARCHAR2(200),
    REV_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
    REV_VAL NUMBER(5)
);

/* REVIEW_COMMENT ���̺�  */
CREATE TABLE REVIEW_COMMENT (
    REVC_NUM VARCHAR2(10) CONSTRAINT REVIEW_COMMENT_REVR_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(50) CONSTRAINT REVIEW_COMMENT_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    REV_NUM VARCHAR2(10) CONSTRAINT REVIEW_COMMENT_REV_NUM_FK REFERENCES REVIEW,
    REVC_CONT VARCHAR2(1000) NOT NULL,
    REVC_DATE VARCHAR2(20) NOT NULL
);


/* ANNOUNCEMENT ���̺�  */
CREATE TABLE ANNOUNCEMENT ( 
    ANN_NUM VARCHAR2(10) CONSTRAINT ANNOUNCEMENT_ANN_NUM_PK PRIMARY KEY, 
    MEG_EMAIL VARCHAR2(50) CONSTRAINT ANNOUNCEMEN_MEG_EMAIL_FK REFERENCES MESSAGE, 
    ANN_CONT VARCHAR2(3000) NOT NULL,
    ANN_IMG VARCHAR2(200), 
    ANN_DATE VARCHAR2(20) NOT NULL, 
    ANN_VIEW NUMBER(10)
);

/* CHATROOM ���̺�  */
CREATE TABLE CHATROOM (
    CHATROOM_ID VARCHAR2(20) CONSTRAINT CHATROOM_CHATROOM_ID_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT CHATROOM_CL_NUM_FK REFERENCES CLIENT,
    BP_ID VARCHAR2(50) CONSTRAINT CHATROOM_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    BP_TYPE NUMBER(1)
);

/* CHATMESSAGE ���̺�  */
CREATE TABLE CHATMESSAGE (
    MESSAGE_ID VARCHAR2(20) CONSTRAINT CHATMESSAGE_MESSAGE_ID_PK PRIMARY KEY,
    MESSAGE_SENDER VARCHAR(20),
    MESSAGE_RECEIVER VARCHAR(20),
    MESSAGE_CONTENT VARCHAR(2000),
    MESSAGE_SENDTIME TIMESTAMP,
    CHATROOM_ID CONSTRAINT CHATMESSAGE_CHATROOM_ID_FK REFERENCES CHATROOM,
    UNREAD_COUNT NUMBER(1),
    INVISIBLE_CLIENT NUMBER(1),
    INVISIBLE_BP NUMBER(1),
);

/* POINT ���̺�  */
CREATE TABLE POINT ( 
 POINT_NUM VARCHAR2(20) CONSTRAINT POINT_POINT_NUM_PK PRIMARY KEY,
 POINT_NAME VARCHAR2(20) NOT NULL,
 EXP_TYPE VARCHAR2(20) NOT NULL,
 SCORE NUMBER(7) NOT NULL
);


/* MYPOINT ���̺�  */
CREATE TABLE MYPOINT (
 CL_NUM VARCHAR2(50) CONSTRAINT MYPOINT_CL_NUM_FK REFERENCES CLIENT NOT NULL,
 POINT_NUM VARCHAR2(20),
 INDEXS NUMBER(1),
 EXP_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD'),
 EXP_TYPE VARCHAR2(20),
 EXP_FROM VARCHAR2(20),
 EXP_ID VARCHAR2(20),
 EXP_POINT NUMBER(5) DEFAULT 0,
 CURR_POINT NUMBER(5) DEFAULT 0 NOT NULL
);


/* CTA ���̺�  */
CREATE TABLE CTA ( 
    CM_CODE VARCHAR2(20) CONSTRAINT CTA_CM_CODE_PK PRIMARY KEY,
    CM_TYPE VARCHAR2(20) NOT NULL,
    PRICE NUMBER(7) NOT NULL
);


/* CTA_CHARGE ���̺�  */
CREATE TABLE CTA_CHARGE ( 
    CHRG_NUM VARCHAR2(20) CONSTRAINT CTA_CHARGE_CHRG_NUM_PK PRIMARY KEY,
    CM_CODE VARCHAR2(20) NOT NULL CONSTRAINT CTA_CHARGE_CM_CODE_FK REFERENCES CTA,
    BP_ID VARCHAR2(50) CONSTRAINT CTA_CHARGE_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    CHRG_DATE VARCHAR2(20) NOT NULL
);


/* LIKE ���̺�  */
CREATE TABLE LIKES (
    LIKE_NUM VARCHAR2(20) CONSTRAINT LIKES_LIKE_NUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT LIKES_CL_NUM_FK REFERENCES CLIENT,
    HAR_NUM VARCHAR2(20) CONSTRAINT LIKES_HAR_NUM_FK REFERENCES HAIR_SALON,
    HOS_NUM VARCHAR2(20) CONSTRAINT LIKES_HOS_NUM_FK REFERENCES HOSPITAL
);


/* M_CAL ���̺�  */
CREATE TABLE M_CAL (
    MCAL_NUM VARCHAR2(10) CONSTRAINT M_CAL_MCAL_NUM_PK PRIMARY KEY,
    MEG_EMAIL VARCHAR2(50) CONSTRAINT M_CAL_MEG_EMAIL_FK REFERENCES MANAGER NOT NULL, 
    MCAL_PRICE VARCHAR2(10) NOT NULL, 
    MCAL_DATE VARCHAR2(20) NOT NULL
);


/* B_CAL ���̺�  */
CREATE TABLE B_CAL (
    BCAL_NUM VARCHAR2(10) CONSTRAINT B_CAL_BCAL_NUM_PK PRIMARY KEY, 
    BP_ID VARCHAR2(20) CONSTRAINT B_CAL_BP_ID_FK REFERENCES BUSINESS_PARTNER, 
    BCAL_PRICE VARCHAR2(10) NOT NULL,
    BCAR_DATE VARCHAR2(20) NOT NULL 
);


--INSERT TEMPORARY USER INFORMATION
INSERT INTO USERS VALUES('kimttobi@ttobi.com', 'KIM TTOBI', 'TTOBI', '2019-03-01',  '1234ttobi', 01012345678, 'JONGRO, SEOUL, REPUBLIC OF KOREA');


/* �⺻ ������ */

INSERT INTO BUSINESS_PARTNER VALUES('BP1', '1111', '�����1', '01000000001', '�Ǻ�����', '0000000000001', '1', '�̸���1', 0, 1, 0);
INSERT INTO BUSINESS_PARTNER VALUES('BP2', '2222', '�����2', '01000000002', '�Ǻ�����', '0000000000002', '2', '�̸���2', 0, 1, 0);
INSERT INTO BUSINESS_PARTNER VALUES('BP3', '3333', '�����3', '01000000003', '�Ǻ�����', '0000000000003', '3', '�̸���3', 0, 1, 0);
INSERT INTO BUSINESS_PARTNER VALUES('BP4', '4444', '�����4', '01000000004', '�Ǻ�����', '0000000000004', '4', '�̸���4', 0, 1, 0);
INSERT INTO BUSINESS_PARTNER VALUES('BP5', '5555', '�����5', '01000000005', '�Ǻ�����', '0000000000005', '5', '�̸���5', 0, 1, 0);

INSERT INTO CLIENT VALUES('CL1', 'user1@user.com', '1111', '�г���1', '�����1', '01010000001', NULL, NULL);
INSERT INTO CLIENT VALUES('CL2', 'user2@user.com', '2222', '�г���2', '�����2', '01010000002', NULL, NULL);
INSERT INTO CLIENT VALUES('CL3', 'user3@user.com', '3333', '�г���3', '�����3', '01010000003', NULL, NULL);
INSERT INTO CLIENT VALUES('CL4', 'user4@user.com', '4444', '�г���4', '�����4', '01010000004', NULL, NULL);
INSERT INTO CLIENT VALUES('CL5', 'user5@user.com', '5555', '�г���5', '�����5', '01010000005', NULL, NULL);

INSERT INTO HAIR_SALON VALUES('HA1', 'BP1', '�̿��1', '�ּ�', '010-0000-0000', '09��~18��', '�̿�� �Ұ� �׽�Ʈ', 0);
INSERT INTO HAIR_SALON VALUES('HA2', 'BP2', '�̿��2', '�ּ�', '010-0000-0000', '09��~18��', '�̿�� �Ұ� �׽�Ʈ', 0);
INSERT INTO HAIR_SALON VALUES('HA3', 'BP3', '�̿��3', '�ּ�', '010-0000-0000', '09��~18��', '�̿�� �Ұ� �׽�Ʈ', 0);
INSERT INTO HAIR_SALON VALUES('HA4', 'BP4', '�̿��4', '�ּ�', '010-0000-0000', '09��~18��', '�̿�� �Ұ� �׽�Ʈ', 0);
INSERT INTO HAIR_SALON VALUES('HA5', 'BP5', '�̿��5', '�ּ�', '010-0000-0000', '09��~18��', '�̿�� �Ұ� �׽�Ʈ', 0);

INSERT INTO REVIEW VALUES('RV1', 'BP1', 'CL1', '�г���1', '���䳻��1', NULL, TO_CHAR(SYSDATE, 'YYYYMMDD'), 1);
INSERT INTO REVIEW VALUES('RV2', 'BP1', 'CL2', '�г���2', '���䳻��2', NULL, TO_CHAR(SYSDATE, 'YYYYMMDD'), 2);
INSERT INTO REVIEW VALUES('RV3', 'BP1', 'CL3', '�г���3', '���䳻��3', NULL, TO_CHAR(SYSDATE, 'YYYYMMDD'), 3);
INSERT INTO REVIEW VALUES('RV4', 'BP1', 'CL4', '�г���4', '���䳻��4', NULL, TO_CHAR(SYSDATE, 'YYYYMMDD'), 4);
INSERT INTO REVIEW VALUES('RV5', 'BP1', 'CL5', '�г���5', '���䳻��5', NULL, TO_CHAR(SYSDATE, 'YYYYMMDD'), 5);
INSERT INTO REVIEW VALUES('RV6', 'BP2', 'CL1', '�г���1', '���䳻��2-1', NULL, TO_CHAR(SYSDATE, 'YYYYMMDD'), 5);

INSERT INTO HAR_RESERVATION VALUES('HOR1', 'M1', '1', '57', 1, '1', TO_CHAR(SYSDATE, 'YYYYMMDD'), 0);
INSERT INTO HAR_RESERVATION VALUES('HOR2', 'M2', '1', '57', 2, '2', TO_CHAR(SYSDATE, 'YYYYMMDD'), 1);
INSERT INTO HAR_RESERVATION VALUES('HOR3', 'M3', '1', '57', 3, '3', TO_CHAR(SYSDATE, 'YYYYMMDD'), 2);

/* �޼���  */
INSERT INTO MESSAGE VALUES('M1', '�˸�����1');
INSERT INTO MESSAGE VALUES('M2', '�˸�����2');
INSERT INTO MESSAGE VALUES('M3', '�˸�����3');
INSERT INTO MESSAGE VALUES('M4', '�˸�����4');
INSERT INTO MESSAGE VALUES('M5', '�˸�����5');

/* ����Ʈ  */
INSERT INTO POINT VALUES('PO1', '���', '���', 0);
INSERT INTO POINT VALUES('PO2', '���', '���', 0);
INSERT INTO POINT VALUES('PO3', '�۾���', '����', 100);
INSERT INTO POINT VALUES('PO4', '����', '����', 300);

/* ��������Ʈ */
INSERT INTO MYPOINT VALUES('CL1', 'PO4', SEQ_MYPOINT.NEXTVAL, TO_CHAR(SYSDATE, 'YYYYMMDD'), '����', '�̿��1', 'RV1', 500, 500);
INSERT INTO MYPOINT VALUES('CL1', 'PO4', SEQ_MYPOINT.NEXTVAL, TO_CHAR(SYSDATE, 'YYYYMMDD'), '����', '�̿��2', 'RV6', 500, 1000);
INSERT INTO MYPOINT VALUES('CL1', 'PO1', SEQ_MYPOINT.NEXTVAL, TO_CHAR(SYSDATE, 'YYYYMMDD'), '���', '�̿��3', 'HAP1', -1000, 0);
INSERT INTO MYPOINT VALUES('CL1', 'PO2', SEQ_MYPOINT.NEXTVAL, TO_CHAR(SYSDATE, 'YYYYMMDD'), '���', '�̿��3', 'HAP1', 1000, 1000);



COMMIT;

