/* DROP 테이블 */
DROP TABLE B_CAL CASCADE CONSTRAINTS;
DROP TABLE M_CAL CASCADE CONSTRAINTS;
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE CTA_CHARGE CASCADE CONSTRAINTS;
DROP TABLE CTA CASCADE CONSTRAINTS;
DROP TABLE MYPOINT CASCADE CONSTRAINTS;
DROP TABLE POINT CASCADE CONSTRAINTS;
DROP TABLE CHATTING CASCADE CONSTRAINTS;
DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS;
DROP TABLE REVIEW_COMMENT CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE QNA_COMMENT CASCADE CONSTRAINTS;
DROP TABLE QNA_BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL_DAYOFF CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL_IMAGE CASCADE CONSTRAINTS;
DROP TABLE HOS_PAY CASCADE CONSTRAINTS;
DROP TABLE HOS_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE MEDICAL_TYPE CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL CASCADE CONSTRAINTS;
DROP TABLE HAIR_DAYOFF CASCADE CONSTRAINTS;
DROP TABLE HAIR_SALON_IMG CASCADE CONSTRAINTS;
DROP TABLE HAR_PAY CASCADE CONSTRAINTS;
DROP TABLE HAR_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE STYLE CASCADE CONSTRAINTS;
DROP TABLE HAIR_SALON CASCADE CONSTRAINTS;
DROP TABLE MY_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE PET_INFO CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_PARTNER CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;

/* DROP SEQUENCE */
DROP SEQUENCE SEQ_BUSINESS_PARTNER;
DROP SEQUENCE SEQ_CLIENT;
DROP SEQUENCE SEQ_ANNOUNCEMENT;
DROP SEQUENCE SEQ_QNA_BOARD;
DROP SEQUENCE SEQ_QNA_COMMENT;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_REVIEW_COMMENT;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_COMMENT;
DROP SEQUENCE SEQ_CHATTING;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_CTA;
DROP SEQUENCE SEQ_CTA_CHARGE;
DROP SEQUENCE SEQ_LIKES;
DROP SEQUENCE SEQ_PET_INFO;
DROP SEQUENCE SEQ_HAIR_SALON;
DROP SEQUENCE SEQ_HAR_RESERVATION;
DROP SEQUENCE SEQ_HAR_PAY;
DROP SEQUENCE SEQ_LIKES;
DROP SEQUENCE SEQ_STYLE;
DROP SEQUENCE SEQ_HOSPITAL;
DROP SEQUENCE SEQ_HOS_RESERVATION;
DROP SEQUENCE SEQ_HOS_PAY;
DROP SEQUENCE SEQ_MEDICAL_TYPE;

/* CREATE SEQUENCE */
CREATE SEQUENCE SEQ_BUSINESS_PARTNER
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CLIENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_ANNOUNCEMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_QNA_BOARD
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_QNA_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_REVIEW
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_BOARD
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_BOARD_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CHATTING
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_MESSAGE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_POINT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CTA
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CTA_CHARGE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_LIKES
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_PET_INFO
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAIR_SALON
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAR_RESERVATION
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAR_PAY
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_STYLE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOSPITAL
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOS_RESERVATION
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOS_PAY
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_MEDICAL_TYPE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;



/* MANAGER 테이블 */
CREATE TABLE MANAGER ( 
 MEG_EMAIL VARCHAR2(50) CONSTRAINT MANAGER_MEG_EMAIL_PK PRIMARY KEY,
 MEG_PASSWORD VARCHAR2(30) NOT NULL 
);

/* BUSINESS_PARTNER 테이블 */
CREATE TABLE BUSINESS_PARTNER ( 
 BP_ID VARCHAR2(20) CONSTRAINT BUSINESS_PARTNER_BP_ID_PK PRIMARY KEY, 
 BP_PWD VARCHAR2(30) NOT NULL, 
 BP_NAME VARCHAR2(20) NOT NULL, 
 BP_TEL VARCHAR2(20) NOT NULL UNIQUE,
 BP_BANK VARCHAR2(20), 
 BP_ACNT VARCHAR2(20), 
 BP_EMAIL VARCHAR2(20) NOT NULL UNIQUE,
 BP_NUM VARCHAR2(20) NOT NULL,
 BP_TYPE NUMBER(1) DEFAULT 0 NOT NULL,
 BP_APRVE NUMBER(1) DEFAULT 0 NOT NULL
);


/* CLIENT 테이블 */
CREATE TABLE CLIENT (
 CL_NUM VARCHAR2(20) CONSTRAINT CLIENT_CL_NUM_PK PRIMARY KEY,
 CL_EMAIL VARCHAR2(20) NOT NULL UNIQUE,
 CL_PWD VARCHAR2(30) NOT NULL,
 CL_NICKNAME VARCHAR2(20) NOT NULL UNIQUE,
 CL_NAME VARCHAR2(20) NOT NULL,
 CL_TEL VARCHAR2(20) NOT NULL UNIQUE
);


/* PET_INFO 테이블 */
CREATE TABLE PET_INFO (
    PET_NUM VARCHAR2(20) CONSTRAINT PET_INFO_PET_NUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT PET_INFO_CL_NUM_FK REFERENCES CLIENT ON DELETE CASCADE NOT NULL,
    PET_NAME VARCHAR2(20) NOT NULL,
    PET_KIND VARCHAR2(20) NOT NULL,
    PET_BIRTH VARCHAR2(20) NOT NULL,
    PET_GEN VARCHAR2(20) NOT NULL,
    PET_NEUT NUMBER(1),
    PET_EXPER VARCHAR2(20),
    PET_VACCIN VARCHAR2(20),
    PET_BITE VARCHAR2(20),
    KNEECAP VARCHAR2(10),
    DISLIKE VARCHAR2(20),
    PET_OTHERS VARCHAR2(20),
    PET_IMG VARCHAR2(20),
    MBTI VARCHAR2(20)
);


/* MESSAGE 테이블 */
CREATE TABLE MESSAGE (
    MSG_NUM VARCHAR2(20) CONSTRAINT MESSAGE_MSG_NUM_PK PRIMARY KEY,
    MSG_CONT VARCHAR2(200) NOT NULL
);


/* MY_MESSAGE 테이블 */
CREATE TABLE MY_MESSAGE (
    MSG_NUM VARCHAR2(20) CONSTRAINT MY_MESSAGE_MSG_NUM_FK REFERENCES MESSAGE ON DELETE CASCADE NOT NULL,
    CL_NUM VARCHAR2(20) CONSTRAINT MY_MESSAGE_CL_NUM_FK REFERENCES CLIENT ON DELETE CASCADE
    NOT NULL,
    MSG_DATE VARCHAR2(200) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);


/* HAIR_SALON 테이블 */
CREATE TABLE HAIR_SALON (
    HAR_NUM VARCHAR2(20) CONSTRAINT HAIR_SALON_HAR_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT HAIR_SALON_BP_ID_FK REFERENCES BUSINESS_PARTNER ON DELETE CASCADE NOT NULL,
    HAR_NAME VARCHAR2(20) NOT NULL,
    HAR_ADDR VARCHAR2(300) NOT NULL,
    HAR_TEL VARCHAR2(20) NOT NULL,
    HOPEN_TIME VARCHAR2(100),
    HAR_MINFO VARCHAR2(500),
    HAR_CLICK NUMBER(7) NOT NULL
);


/* STYLE 테이블 */
CREATE TABLE STYLE (
    STYLE_NUM VARCHAR2(20) CONSTRAINT STYLE_STYLE_NUM_PK PRIMARY KEY,
    HAR_NUM VARCHAR2(20) CONSTRAINT STYLE_HAR_NUM_FK REFERENCES HAIR_SALON ON DELETE CASCADE
    NOT NULL,
    STYLE_NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER(7) NOT NULL
);


/* HAR_RESERVATION 테이블 */
CREATE TABLE HAR_RESERVATION (
    HAR_RNUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_HAR_RNUM_PK PRIMARY KEY,
    MSG_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_MSG_NUM_FK REFERENCES MESSAGE 
    ON DELETE CASCADE NOT NULL,
    CL_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_CL_NUM_FK REFERENCES CLIENT
    ON DELETE CASCADE NOT NULL,
    PET_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_PET_NUM_FK REFERENCES PET_INFO 
    ON DELETE CASCADE NOT NULL,
    STYLE_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_STYLE_NUM_FK REFERENCES STYLE 
    ON DELETE CASCADE NOT NULL,
    HAR_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_HAR_NUM_FK REFERENCES HAIR_SALON 
    ON DELETE CASCADE NOT NULL,
    RES_DATE VARCHAR2(50) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);


/* HAR_PAY 테이블 */
CREATE TABLE HAR_PAY (
    PAY_NUM VARCHAR2(20) CONSTRAINT HAR_PAY_PAY_NUM_PK PRIMARY KEY,
    HAR_RNUM VARCHAR2(20) CONSTRAINT HAR_PAY_HAR_RNUM_FK REFERENCES HAR_RESERVATION
    ON DELETE CASCADE NOT NULL,
    MSG_NUM VARCHAR2(20) CONSTRAINT HAR_PAY_MSG_NUM_FK REFERENCES MESSAGE
    ON DELETE CASCADE NOT NULL,
    CARD_NUM VARCHAR2(20),
    BANK_NUM VARCHAR2(20),
    CARD_NAME VARCHAR2(20),
    BANK_NAME VARCHAR2(20),
    PAY_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
    PAY_PRICE NUMBER(7),
    TOTAL_PRICE NUMBER(7)
);

/* HAIR_SALON_IMG 테이블 */
CREATE TABLE HAIR_SALON_IMG (
    IMG_NUM VARCHAR(7) CONSTRAINT HAIR_SALON_IMG_IMG_NUM_PK PRIMARY KEY,
    HAR_NUM VARCHAR2(20) CONSTRAINT HAIR_SALON_IMG_HAR_NUM_FK REFERENCES HAIR_SALON
    ON DELETE CASCADE NOT NULL,
    HAR_IMG VARCHAR2(500)
);

/* HAIR_DAYOFF 테이블 */
CREATE TABLE HAIR_DAYOFF (
    HAR_NUM VARCHAR2(20) CONSTRAINT HAIR_DAYOFF_HAR_NUM_FK REFERENCES HAIR_SALON
    ON DELETE CASCADE NOT NULL,
    HAR_DAYOFF VARCHAR2(2)
);

/* HOSPITAL 테이블 */
CREATE TABLE HOSPITAL (
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_HOS_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT HOSPITAL_BP_ID_FK REFERENCES BUSINESS_PARTNER
    ON DELETE CASCADE NOT NULL,
    HOS_NAME VARCHAR2(20) NOT NULL,
    HOS_ADDR VARCHAR2(300) NOT NULL,
    HOS_TEL VARCHAR2(20) NOT NULL,
    OPEN_TIME VARCHAR2(20),
    HOS_MINFO VARCHAR2(500),
    HOS_CONN NUMBER(1),
    HOS_CLICK NUMBER(7) DEFAULT 0 NOT NULL
);

/* MEDICAL_TYPE 테이블 */
CREATE TABLE MEDICAL_TYPE (
    MED_NUM VARCHAR2(20) CONSTRAINT MEDICAL_TYPE_MED_NUM_PK PRIMARY KEY,
    MED_NAME VARCHAR2(500) NOT NULL,
    MED_PRICE NUMBER(7) NOT NULL
);

/* HOS_RESERVATION 테이블 */
CREATE TABLE HOS_RESERVATION (
    HOS_RNUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_HOS_RNUM_PK PRIMARY KEY,
    PET_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_PET_NUM_FK REFERENCES PET_INFO
    ON DELETE CASCADE NOT NULL,
    MSG_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_MSG_NUM_FK REFERENCES MESSAGE
    ON DELETE CASCADE NOT NULL,
    CL_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_CL_NUM_FK REFERENCES CLIENT
    ON DELETE CASCADE NOT NULL,
    MED_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_MED_NUM_FK REFERENCES MEDICAL_TYPE
    ON DELETE CASCADE NOT NULL,
    HOS_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_HOS_NUM_FK REFERENCES HOSPITAL
    ON DELETE CASCADE NOT NULL,
    HOS_DATE VARCHAR2(50) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);

/* HOS_PAY 테이블 */
CREATE TABLE HOS_PAY (
    PAY_NUM VARCHAR2(20) CONSTRAINT HOS_PAY_PAY_NUM_PK PRIMARY KEY,
    HOS_RNUM VARCHAR2(20) CONSTRAINT HOS_PAY_HOS_RNUM_FK REFERENCES HOS_RESERVATION 
    ON DELETE CASCADE NOT NULL,
    MSG_NUM VARCHAR2(20) CONSTRAINT HOS_PAY_MSG_NUM_FK REFERENCES MESSAGE 
    ON DELETE CASCADE NOT NULL,
    CARD_NUM VARCHAR2(20),
    BANK_NUM VARCHAR2(20),
    CARD_NAME VARCHAR2(20),
    BANK_NAME VARCHAR2(20),
    PAY_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
    PAY_PRICE NUMBER(7),
    TOTAL_PRICE NUMBER(7)
);

/* HOSPITAL_IMAGE 테이블 */
CREATE TABLE HOSPITAL_IMAGE (
    IMG_NUM VARCHAR2(7) CONSTRAINT HOSPITAL_IMAGE_IMG_NUM_PK PRIMARY KEY,
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_IMAGE_HOS_NUM_FK REFERENCES HOSPITAL
    ON DELETE CASCADE NOT NULL,
    HOS_IMG VARCHAR2(500)
);

/* HOSPITAL_DAYOFF 테이블 */
CREATE TABLE HOSPITAL_DAYOFF (
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_DAYOFF_HOS_NUM_FK REFERENCES HOSPITAL
    ON DELETE CASCADE NOT NULL,
    HOS_DAYOFF VARCHAR2(2)
);

/* BOARD 테이블 */
CREATE TABLE BOARD ( 
 BO_NUM VARCHAR2(20) CONSTRAINT BOARD_BO_NUM_PK PRIMARY KEY,
 CL_NUM VARCHAR2(20) CONSTRAINT BOARD_CL_NUM_FK REFERENCES CLIENT
 ON DELETE CASCADE NOT NULL,
 BO_TITLE VARCHAR2(100) NOT NULL,
 BO_CONT VARCHAR2(3000) NOT NULL,
 BO_IMG VARCHAR2(200),
 BO_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
 BO_VIEW NUMBER(10) DEFAULT 0 NOT NULL 
);

/* BOARD_COMMENT 테이블 */
CREATE TABLE BOARD_COMMENT ( 
 CO_NUM VARCHAR2(20) CONSTRAINT BOARD_COMMENT_CO_NUM_PK PRIMARY KEY,
 BO_NUM VARCHAR2(20) CONSTRAINT BOARD_COMMENT_CO_NUM_BO_NUM_FK REFERENCES BOARD
 ON DELETE CASCADE NOT NULL,
 CL_NUM VARCHAR2(20) CONSTRAINT BOARD_COMMENT_CL_NUM_FK REFERENCES CLIENT
 ON DELETE CASCADE NOT NULL,
 CO_CONT VARCHAR2(1000) NOT NULL,
 CO_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);

/* QNA_BOARD 테이블 */
CREATE TABLE QNA_BOARD ( 
 QNA_NUM VARCHAR2(20) CONSTRAINT QNA_BOARD_QNA_NUM_PK PRIMARY KEY,
 QNA_TITLE VARCHAR2(100) NOT NULL,
 QNA_CONT VARCHAR2(3000) NOT NULL,
 QNA_IMG VARCHAR2(200),
 QNA_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
 QNA_TYPE NUMBER(1) NOT NULL,
 QNA_WR VARCHAR2(50),
 QNAR_CHK NUMBER(1) DEFAULT 0
);

/* QNA_COMMENT 테이블 */
CREATE TABLE QNA_COMMENT ( 
 QNAC_NUM VARCHAR2(20) CONSTRAINT QNAC_COMMENT_QNAR_NUM_PK PRIMARY KEY, 
 MEG_EMAIL VARCHAR2(50) CONSTRAINT QNA_COMMENT_MEG_EMAIL_FK REFERENCES MESSAGE
 ON DELETE CASCADE NOT NULL, 
 QNA_NUM VARCHAR2(50) CONSTRAINT QNA_COMMENT_QNA_NUM_FK REFERENCES QNA_BOARD
 ON DELETE CASCADE NOT NULL, 
 QNAC_CONT VARCHAR2(1000), 
 QNAC_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL 
);


/* REVIEW 테이블 */
CREATE TABLE REVIEW (
    REV_NUM VARCHAR2(20) CONSTRAINT REVIEW_REV_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT REVIEW_BP_ID_FK REFERENCES BUSINESS_PARTNER
    ON DELETE CASCADE NOT NULL,
    CL_NUM VARCHAR2(20) CONSTRAINT REVIEW_CL_NUM_FK REFERENCES CLIENT
    ON DELETE CASCADE NOT NULL,
    REV_CONT VARCHAR2(3000),
    REV_IMG VARCHAR2(200),
    REV_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
    REV_VAL NUMBER(5),
    REV_VIEW NUMBER(10)
);


/* REVIEW_COMMENT 테이블 */
CREATE TABLE REVIEW_COMMENT (
 REVC_NUM VARCHAR2(20) CONSTRAINT REVIEW_COMMENT_REVR_NUM_PK PRIMARY KEY,
 BP_ID VARCHAR2(50) CONSTRAINT REVIEW_COMMENT_BP_ID_FK REFERENCES BUSINESS_PARTNER
 ON DELETE CASCADE NOT NULL,
 REV_NUM VARCHAR2(10) CONSTRAINT REVIEW_COMMENT_REV_NUM_FK REFERENCES REVIEW
 ON DELETE CASCADE NOT NULL,
 REVC_CONT VARCHAR2(1000) NOT NULL,
 REVC_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);

/* ANNOUNCEMENT 테이블 */
CREATE TABLE ANNOUNCEMENT ( 
 ANN_NUM VARCHAR2(20) CONSTRAINT ANNOUNCEMENT_ANN_NUM_PK PRIMARY KEY, 
 MEG_EMAIL VARCHAR2(50) CONSTRAINT ANNOUNCEMEN_MEG_EMAIL_FK REFERENCES MESSAGE
 ON DELETE CASCADE NOT NULL, 
 ANN_CONT VARCHAR2(3000) NOT NULL,
 ANN_IMG VARCHAR2(200), 
 ANN_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL, 
 ANN_VIEW NUMBER(10)
);

/* CHATTING 테이블 */
CREATE TABLE CHATTING (
 CHAT_NUM VARCHAR2(20)	CONSTRAINT CHATTING_CHAT_NUM_PK PRIMARY KEY,
 BP_ID VARCHAR2(50) CONSTRAINT CHATTING_BP_ID_FK REFERENCES BUSINESS_PARTNER
 ON DELETE CASCADE NOT NULL,
 CL_NUM VARCHAR2(20) CONSTRAINT CHATTING_CL_NUM_FK REFERENCES CLIENT
 ON DELETE CASCADE NOT NULL,
 CHAT_CONT VARCHAR2(1000) NOT NULL,
 SEND_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL 
);

/* POINT 테이블 */
CREATE TABLE POINT ( 
 POINT_NUM VARCHAR2(20) CONSTRAINT POINT_POINT_NUM_PK PRIMARY KEY, 
 POINT_NAME VARCHAR2(10) NOT NULL, 
 SCORE NUMBER(7) NOT NULL
);

/* MYPOINT 테이블 */
CREATE TABLE MYPOINT (
BP_ID VARCHAR2(50) CONSTRAINT MYPOINT_BP_ID_FK REFERENCES BUSINESS_PARTNER,
 POINT_NUM CONSTRAINT MYPOINT_POINT_NUM_FK REFERENCES POINT
 ON DELETE CASCADE NOT NULL,
 INSERT_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
 DELETE_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
 POINT_CURR NUMBER(7) DEFAULT 0 NOT NULL
);

/* CTA테이블 */
CREATE TABLE CTA ( 
 CM_CODE VARCHAR2(20) CONSTRAINT CTA_CM_CODE_PK PRIMARY KEY,
 CM_TYPE VARCHAR2(20) NOT NULL,
PRICE NUMBER(7) NOT NULL
);

/* CTA_CHARGE테이블 */
CREATE TABLE CTA_CHARGE ( 
 CHRG_NUM VARCHAR2(20) CONSTRAINT CTA_CHARGE_CHRG_NUM_PK PRIMARY KEY,
 CM_CODE VARCHAR2(20) CONSTRAINT CTA_CHARGE_CM_CODE_FK REFERENCES CTA
 ON DELETE CASCADE NOT NULL,
 BP_ID VARCHAR2(50) CONSTRAINT CTA_CHARGE_BP_ID_FK REFERENCES BUSINESS_PARTNER
 ON DELETE CASCADE NOT NULL,
 CHRG_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);

/* LIKES 테이블 */
CREATE TABLE LIKES (
 LIKE_NUM VARCHAR2(20) CONSTRAINT LIKES_LIKE_NUM_PK PRIMARY KEY,
 CL_NUM VARCHAR2(20) CONSTRAINT LIKES_CL_NUM_FK REFERENCES CLIENT
 ON DELETE CASCADE NOT NULL,
 HAR_NUM VARCHAR2(20) CONSTRAINT LIKES_HAR_NUM_FK REFERENCES HAIR_SALON
 ON DELETE CASCADE NOT NULL,
 HOS_NUM VARCHAR2(20) CONSTRAINT LIKES_HOS_NUM_FK REFERENCES HOSPITAL
 ON DELETE CASCADE NOT NULL
);


/* M_CAL 테이블 */
CREATE TABLE M_CAL (
 MCAL_NUM VARCHAR2(20) CONSTRAINT M_CAL_MCAL_NUM_PK PRIMARY KEY,
 MEG_EMAIL VARCHAR2(50) CONSTRAINT M_CAL_MEG_EMAIL_FK REFERENCES MANAGER 
 ON DELETE CASCADE NOT NULL, 
 MCAL_PRICE VARCHAR2(10) NOT NULL, 
 MCAL_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);

/* B_CAL 테이블 */
CREATE TABLE B_CAL (
 BCAL_NUM VARCHAR2(20) CONSTRAINT B_CAL_BCAL_NUM_PK PRIMARY KEY, 
 BP_ID VARCHAR2(20) CONSTRAINT B_CAL_BP_ID_FK REFERENCES BUSINESS_PARTNER
 ON DELETE CASCADE NOT NULL, 
 BCAL_PRICE VARCHAR2(10) NOT NULL,
 BCAR_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL
);